### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by rpocase** [ThomasAitken/Scrapy-Testmaster#2]
I would like to see an example project that is using this successfully. The documentation is a extensive (which is great!), but wading through and figuring out exactly what I need to care about to start being productive is pretty daunting. A minimal example project utilizing this tool would go a great deal to demonstrating what different settings do in the context of a specific spider and exactly what to put in a config.py to add useful validations.

**Comment by ThomasAitken** [comment]
Yes, I was thinking I might need this. I'll try to get one up soon.

**Comment by ThomasAitken** [comment]
Let me know if you have any thoughts on the example project that I've just added.
