### ISSUE TITLE
some settings in config.py seem not to overwrite settings from settings.py

### ISSUE THREAD

**Issue by hathschi** [ThomasAitken/Scrapy-Testmaster#4]
In order to have individual fields to be ignored or asserted to be scraped in each spider of our project, we tried to set the SKIPPED_FIELDS and PRIMARY_ITEM_FIELDS variables in testmaster/tests/spider_name/parse/config.py to overwrite the TESTMASTER_SKIPPED_FIELDS and TESTMASTER_PRIMARY_ITEM_FIELDS variables in project_name/settings.py.
However this seems not to happen.
In line 251 of scrapy_testmaster/utils.py:  

`skipped_local = cb_settings.REQUEST_SKIPPED_FIELDS`  

there seems to be a copy-paste bug (we expected "cb_settings.SKIPPED_FIELDS" there)  
But also (ab)using the REQUEST_SKIPPED_FIELDS variable did not ignore the fields, so there seems to be another issue.  
The variable PRIMARY_ITEM_FIELDS has a similar issue.  
The variable INCLUDED_SETTINGS in config.py on the other hand works fine, so the problem is not the config.py itself.  

Bug reproducing:  

config.py:  

```
SKIPPED_FIELDS = ["timestamp"]  
REQUEST_SKIPPED_FIELDS = ["timestamp"]  
PRIMARY_ITEM_FIELDS = ["some_nonexisting_field"]  
INCLUDED_SETTINGS = ["SKIPPED_FIELDS","TESTMASTER_SKIPPED_FIELDS","PRIMARY_ITEM_FIELDS","TESTMASTER_PRIMARY_ITEM_FIELDS","REQUEST_SKIPPED_FIELDS","TESTMASTER_REQUEST_SKIPPED_FIELDS"]
```
  
settings.py:  
  
```
TESTMASTER_SKIPPED_FIELDS = ["some_nonexisting_field"]  
TESTMASTER_REQUEST_SKIPPED_FIELDS = ["some_nonexisting_field"]  
TESTMASTER_PRIMARY_ITEM_FIELDS = ["count"]  
TESTMASTER_INCLUDED_SETTINGS = []
```
  
behavior:  
  
test is created without error even though this should be prevented by  
`PRIMARY_ITEM_FIELDS = ["some_nonexisting_field"]`  
fixture is not created as expected when setting  
`TESTMASTER_PRIMARY_ITEM_FIELDS = ["some_nonexisting_field"]`  
  
check of the fixture fails because of the timestamp even though this should be prevented by  
`SKIPPED_FIELDS = ["timestamp"]`  
check is ok as expected when setting  
`TESTMASTER_SKIPPED_FIELDS = ["timestamp"]`  
  
test_fixture1.bin contains settings dictionary as expected as set by the  
`INCLUDED_SETTINGS = ...`  
  
test_fixture1.bin:  
`...,"settings": {"SKIPPED_FIELDS": "None", "TESTMASTER_SKIPPED_FIELDS": ["some_nonexisting_field"], "PRIMARY_ITEM_FIELDS": "None", "TESTMASTER_PRIMARY_ITEM_FIELDS": ["count"], "REQUEST_SKIPPED_FIELDS": "None", "TESTMASTER_REQUEST_SKIPPED_FIELDS": ["some_nonexisting_field"]},...`  
  
(the same output is created when putting the list in TESTMASTER_INCLUDED_SETTINGS instead.)  
According to this output, the fields from the config.py are not set.  
  
Our workaround is to setting individual environment variables for settings.py when creating or checking the fixtures, but we would rather have the settings written permanently into config.py.

**Comment by ThomasAitken** [comment]
Thanks for your issue. I'll have a look at this in the coming days.

**Comment by ThomasAitken** [comment]
Just by way of follow-up, I'm going to launch a significant update to this package within the next 24-48 hours which should resolve this and other issues.

**Comment by ThomasAitken** [comment]
I believe I have resolved all of the problems you described in the above. In the latest release, I have also changed the behaviour of the unittest commands so that they validate the output according to the custom rules, just as the `parse` or `update` commands do. Please do let me know if something is still amiss.
